### ISSUE TITLE
Windows 10, emoji's not showing up in dropdown

### ISSUE THREAD

**Issue by CalebKester** [ethanal/SublimeEmoji#1]
Most of the emojis show up as boxes in windows 10 in the command pallet but render just fine when inserted into a document.

**Comment by gaglage** [comment]
same problem w10

**Comment by svensson-david** [comment]
For anyone else looking around, this should probably be addressed in the Sublime issues instead. The quick panel has known font issues and the font is not customizable within the themes. More information can be found [here](https://github.com/SublimeTextIssues/Core/issues/1314) among other places.

Edit, saw now that this bug is also referenced in the other thread.
